package dev.uniqueman.fullstack_app_spring_boot.Entity;

public enum ErrorCode {
    USERNAME_ALREADY_EXISTS,
    USERNAME_NOT_FOUND,
    ADMIN_ALREADY_INITIALIZED,
    INTERNAL_SERVER_ERROR,
    DATA_INTEGRITY_VIOLATION,
    FIELD_VALIDATION_FAILED,
    USER_AUTHENTICATION_FAILED,
    JWT_AUTHENTICATION_FAILED,
    TOKEN_MANAGEMENT_ERROR
}

