FROM node:22.10.0 AS build

ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

WORKDIR /app
COPY package*.json ./

RUN npm install 

COPY . .

RUN npm run build 

# Use Nginx to serve the frontend
FROM nginx:latest

# Copy the custom nginx configuration file
COPY custom-nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/build /usr/share/nginx/html 

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

